import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  Sparkles, 
  Send, 
  Loader2, 
  CheckCircle,
  AlertTriangle,
  GitFork,
  ArrowRight
} from 'lucide-react';
import { api } from '../store/authStore';
import { useWorkflowStore } from '../store/workflowStore';

export default function AiAssistant() {
  const navigate = useNavigate();
  const { createWorkflow, fetchWorkflows } = useWorkflowStore();

  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState(null);
  const [logsText, setLogsText] = useState('');

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!prompt.trim()) return;

    setLoading(true);
    setResponse(null);
    setLogsText('Communicating with Gemini AI engine...\nSynthesizing API node DAG structures...\n');

    try {
      const res = await api.post('/ai/generate-workflow', { prompt });
      const definition = res.data.data.workflow;
      
      setLogsText((prev) => prev + 'Workflow JSON generated successfully!\nValidating DAG constraints...');
      setResponse(definition);
    } catch (err) {
      setLogsText((prev) => prev + '\nError: Failed to generate workflow. Review prompt logic.');
    } finally {
      setLoading(false);
    }
  };

  const handleLoadGeneratedWorkflow = async () => {
    if (!response) return;

    setLoading(true);
    try {
      // Create workflow draft using details generated by Gemini
      const newFlow = await createWorkflow(
        response.name || 'AI Generated Workflow',
        response.description || 'Generated from natural language description',
        ['ai-generated']
      );

      if (newFlow) {
        // Save draft nodes/edges
        await api.put(`/workflows/${newFlow._id}`, {
          draftNodes: response.nodes || [],
          draftEdges: response.edges || [],
        });

        alert('AI workflow successfully generated and loaded onto canvas!');
        navigate(`/workflows/${newFlow._id}`);
      }
    } catch (err) {
      alert('Failed to deploy generated workflow.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      {/* Title */}
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-slate-100 flex items-center space-x-2">
          <Sparkles className="text-brand-400" size={28} />
          <span>Orchest AI Architect</span>
        </h1>
        <p className="text-slate-400 mt-1">
          Describe your API flow in plain English. Gemini will design and construct the orchestration graph automatically.
        </p>
      </div>

      {/* Main chat interface */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2 space-y-4">
          <form onSubmit={handleGenerate} className="glass-panel p-6 space-y-4">
            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Prompt / Instructions</label>
              <textarea
                required
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                rows={4}
                placeholder="Create an API that validates PAN, fetches user details from DummyJSON, transforms the response to a standardized format, and returns the response."
                className="w-full bg-slate-950 border border-slate-800 rounded-xl py-3 px-4 text-slate-100 placeholder-slate-600 focus:outline-none focus:border-brand-500 focus:ring-1 focus:ring-brand-500 transition resize-none text-sm"
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full bg-gradient-to-r from-brand-600 to-indigo-600 hover:from-brand-500 hover:to-indigo-500 disabled:opacity-50 text-slate-100 font-semibold py-3 px-4 rounded-xl flex items-center justify-center space-x-2 shadow-glow-brand"
            >
              {loading ? (
                <>
                  <Loader2 className="animate-spin" size={18} />
                  <span>Synthesizing API Workflow...</span>
                </>
              ) : (
                <>
                  <Send size={16} />
                  <span>Generate Workflow DAG</span>
                </>
              )}
            </button>
          </form>

          {/* AI Output Generation details */}
          {logsText && (
            <div className="glass-panel p-5 space-y-3">
              <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider">System Logs</h3>
              <pre className="bg-slate-950 p-3 rounded-lg border border-slate-900 font-mono text-[10px] text-slate-400 whitespace-pre-wrap">
                {logsText}
              </pre>
            </div>
          )}
        </div>

        {/* Info panel / Deploy triggers */}
        <div className="space-y-5">
          <div className="glass-panel p-6 flex flex-col justify-between min-h-[220px]">
            <div>
              <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Generated Blueprint</h3>
              {response ? (
                <div className="space-y-3">
                  <div className="flex items-center space-x-2 text-emerald-400 text-sm font-semibold">
                    <CheckCircle size={16} />
                    <span>DAG validation passed</span>
                  </div>
                  <h4 className="text-sm font-bold text-slate-200 mt-1">{response.name}</h4>
                  <p className="text-xs text-slate-400 leading-relaxed">{response.description}</p>
                </div>
              ) : (
                <p className="text-xs text-slate-500 italic">No blueprints generated yet. Submit a prompt instructions query.</p>
              )}
            </div>

            {response && (
              <button
                onClick={handleLoadGeneratedWorkflow}
                className="w-full flex items-center justify-center space-x-2 mt-6 py-2.5 bg-brand-600 hover:bg-brand-500 text-white text-xs font-bold rounded-xl shadow-glow-brand transition"
              >
                <GitFork size={14} />
                <span>Deploy to Canvas</span>
                <ArrowRight size={14} />
              </button>
            )}
          </div>

          {/* Quick templates */}
          <div className="glass-panel p-5 space-y-3">
            <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Try Examples</h3>
            <div className="space-y-2">
              {[
                'Validate user email, write to cache if hit, fetch weather, return JSON.',
                'Run parallel queries to fetch stock price and exchange rates, merge them, and output.',
              ].map((tpl, i) => (
                <button
                  key={i}
                  onClick={() => setPrompt(tpl)}
                  className="w-full text-left text-[11px] text-slate-400 hover:text-slate-200 hover:bg-slate-900/40 p-2 rounded border border-slate-900 transition"
                >
                  {tpl}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
